# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit grouper.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------------------------------------------------
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, fig.align = "center")

required_pkgs <- c(
  "grouper", "ompr", "ompr.roi", "ROI.plugin.glpk", "dplyr", "ggplot2",
  "tidyverse", "kableExtra"
)

for (pkg in required_pkgs) {
  if (!requireNamespace(pkg, quietly = TRUE)) {
    stop("Package not installed: ", pkg)
  }
}

suppressPackageStartupMessages({
  library(grouper)
  library(ompr)
  library(ompr.roi)
  library(ROI.plugin.glpk)
  library(dplyr)
  library(ggplot2)
  library(tidyverse)
})


## ----dba-param-guide, echo=FALSE----------------------------------------------------------------------------------------
dba_param_guide <- tibble::tribble(
  ~parameter,   ~if_increased,                                                          ~trade_off,
  "w1",       "Places greater relative emphasis on pairwise diversity",               "May place less emphasis on skill balance",
  "w2",       "Places greater relative emphasis on reducing skill differences",       "May accept lower pairwise diversity",
  "nmin",     "Requires more students in each active topic-repetition combination",   "Tightens feasibility",
  "nmax",     "Permits more students in each topic-repetition combination",           "Increases flexibility but may permit less even group sizes",
  "rmin",     "Requires more active repetitions of every topic",                      "Tightens feasibility and spreads students across more repetitions",
  "rmax",     "Permits more active repetitions of every topic",                       "Increases flexibility but may fragment the cohort",
  "n_topics", "Requires assignments across more topics when `rmin` is positive",      "Increases model size and may tighten feasibility"
)

knitr::kable(dba_param_guide, booktabs = TRUE,
             col.names = c("Parameter", "If increased", "Trade-off"),
             caption = "Parameter effect guide for the diversity-based assignment model (directional, holding other settings fixed).  Parameter names follow how they appear as arguments in code.") %>%
  kableExtra::kable_styling(font_size = 9, latex_options = c("hold_position")) %>%
  kableExtra::column_spec(1, width = "2cm") %>%
  kableExtra::column_spec(2, width = "5.5cm") %>%
  kableExtra::column_spec(3, width = "5.5cm")


## ----pba-param-guide, echo=FALSE----------------------------------------------------------------------------------------
pba_param_guide <- tibble::tribble(
  ~parameter,   ~if_increased,                                                          ~trade_off,
  "n_topics", "Provides more base topics, each subject to the repetition rules",       "Increases model size and may tighten feasibility",
  "B",        "Adds more subgroups to every topic",                                    "Permits finer organization but adds balancing requirements",
  "nmax",     "Permits more students in each repetition",                              "Increases flexibility but may permit crowded groups",
  "rmin",     "Requires more repetitions of every topic and corresponding subgroup",   "Tightens feasibility and may reduce achievable preference scores",
  "rmax",     "Permits more repetitions",                                              "Increases flexibility but may fragment allocations"
)

knitr::kable(pba_param_guide, booktabs = TRUE,
             col.names = c("Parameter", "If increased", "Trade-off"),
             caption = "Parameter effect guide for the preference-based assignment model (directional, holding other settings fixed).") %>%
  kableExtra::kable_styling(font_size = 9, latex_options = c("hold_position")) %>%
  kableExtra::column_spec(1, width = "2cm") %>%
  kableExtra::column_spec(2, width = "5.5cm") %>%
  kableExtra::column_spec(3, width = "5.5cm")


## ----multirole-param-guide, echo=FALSE----------------------------------------------------------------------------------
multirole_param_guide <- tibble::tribble(
  ~parameter, ~if_increased, ~trade_off,
  "alpha_ta, alpha_gr",
  "Increases the penalty on annual workload spread for the corresponding role",
  "Can improve role-specific fairness at the expense of preference, priority, or protection terms",
  "beta_ta, beta_gr",
  "Increases the reward for the corresponding role's preference scores",
  "Can improve role-specific preference attainment at the expense of other objective terms",
  "phi",
  "Increases the reward for assigning E to individuals with larger scores",
  "Can improve priority alignment at the expense of the other objective terms",
  "rho_ta, rho_gr",
  "Makes the corresponding protected-cohort slack more expensive",
  "Discourages overload but does not alter feasibility because slack remains available",
  "ta_protected_max, gr_protected_max",
  "Raises the corresponding protected cohort's soft threshold",
  "Weakens protection and can reduce the slack penalty; formal feasibility is unchanged",
  "C",
  "Raises every individual's required annual workload from 2C",
  "Requires two additional workload units per person for each unit increase and may cause infeasibility if aggregate demand is incompatible",
  "ta_min, gr_min, e_min",
  "Raises the required minimum for the corresponding role",
  "Tightens feasibility and forces more of that role onto every individual",
  "ta_max, gr_max, e_max",
  "Raises the permitted maximum for the corresponding role",
  "Weakly enlarges the feasible set and may allow greater concentration"
)

knitr::kable(
  multirole_param_guide,
  booktabs = TRUE,
  col.names = c("Parameter", "If increased", "Trade-off"),
  caption = "Parameter effect guide for the multi-role workload allocation model (directional, holding other settings fixed)."
) %>%
  kableExtra::kable_styling(font_size = 9, latex_options = c("hold_position")) %>%
  kableExtra::column_spec(1, width = "3cm") %>%
  kableExtra::column_spec(2, width = "5cm") %>%
  kableExtra::column_spec(3, width = "5cm")




## ----fig-package-architecture, fig.cap="High-level package architecture.", fig.alt="Workflow diagram showing higher-education inputs flowing through data processing, model building, and solving stages, with outputs for solver diagnostics and allocation tables.", out.width="0.92\\linewidth", echo=FALSE, fig.pos='ht'----
knitr::include_graphics("figures/workflow.png")


## ----wrapper-extract-info, eval=FALSE-----------------------------------------------------------------------------------
# df <- extract_info(assignment = "multirole", student_df = S, d_mat = D,
#                    p_ta_mat = P_TA, p_gr_mat = P_GR)


## ----wrapper-prepare-model, eval=FALSE----------------------------------------------------------------------------------
# m <- prepare_model(df, assignment = "multirole",
#                    alpha_ta = a_ta, alpha_gr = a_gr,
#                    beta_ta = b_ta, beta_gr = b_gr,
#                    phi = p, rho_ta = r_ta, rho_gr = r_gr)


## ----wrapper-solve-assignment, eval=FALSE-------------------------------------------------------------------------------
# out <- solve_assignment(model = m, assignment = "multirole", solver = "glpk",
#                         student_df = S, course_codes = J)


## ----constructed-dba-data-----------------------------------------------------------------------------------------------
dba_gc_ex001


## ----constructed-dba-run------------------------------------------------------------------------------------------------
dba_ex1_list <- extract_info(assignment = "diversity", dframe = dba_gc_ex001, 
                        demographic_cols = 2, skills = 3, self_formed_groups = 4)

dba_ex1_model <- prepare_model(dba_ex1_list, assignment = "diversity", 
                               w1 = 1.0, w2 = 0.0, 
                               n_topics = 2, nmin = 2, nmax = 2, rmin = 1, rmax = 1 )

dba_ex1_result <- solve_assignment(dba_ex1_model, "diversity", solver="glpk", 
                                   verbose=FALSE, 
                                   dframe = dba_gc_ex001,  group_names="groups")


## ----constructed-dba-2, echo=FALSE--------------------------------------------------------------------------------------
knitr::kable(dba_ex1_result$output, booktabs=TRUE,
             col.names = c("topic", "rep", "group", "id", "major", "skill"),
             caption = "The assigned groupings for the constructed DBA dataset. Students 2 and 4 have been assigned to topic 1 and students 1 and 3 to topic 2.") %>% 
  kableExtra::kable_styling(latex_options = c("hold_position"))


## ----constructed-pba-data-----------------------------------------------------------------------------------------------
pba_gc_ex002


## ----constructed-pba-pref-----------------------------------------------------------------------------------------------
pba_prefmat_ex002


## ----constructed-pba-run------------------------------------------------------------------------------------------------
pba_ex2_list <- extract_info(assignment = "preference", 
                             dframe = pba_gc_ex002, self_formed_groups = 2, 
                             pref_mat = pba_prefmat_ex002)

pba_ex2_model <- prepare_model(pba_ex2_list, assignment = "preference", 
                               n_topics = 2, B = 2, nmin = 2, nmax = 2, 
                               rmin = 1, rmax = 1)

pba_ex2_result <- solve_assignment(pba_ex2_model,   
                                   assignment = "preference", verbose=FALSE, 
                                   dframe = pba_gc_ex002,   
                                   params_list = list(n_topics = 2, B = 2),   
                                   group_names = "grouping")


## ----constructed-pba-2, echo=FALSE--------------------------------------------------------------------------------------
tmp <- arrange(pba_ex2_result$output, topic2, subtopic)
knitr::kable(tmp, booktabs=TRUE,
             col.names = c("topic", "subtopic", "rep", "group", "size", "id"),
             caption = "The assigned groupings for the constructed PBA dataset. The number of rows in this dataset is equal to the number of students in the course.") %>% 
  kableExtra::kable_styling(latex_options = c("hold_position"))


## ----dba-past-1, echo=FALSE, fig.align='center', fig.cap='Comparison between grouper allocation and manual allocation for diversity-based groupings in an interdisciplinary course. The top row corresponds to the outcomes if grouper had been available to carry out the allocation. The bottom row consists of the manual allocation outcomes. Notice that group 2 in the manual assignment was heavily imbalanced.', out.width='85%', fig.pos='ht'----
knitr::include_graphics("figures/dba_past_semesters_allocation.png")


## ----pba-past-1, echo=FALSE---------------------------------------------------------------------------------------------
pba_pref_df <- tibble(sem = 1:4,
		      manual = c(8.16, 13.10, 12.70, 9.48),
		      grouper = c(9.47, 13.30, 13.50, 9.66),
		      class_size = c(62L, 108L, 89L, 151L),
		      n_topics = c(4L,7L,7L,5L),
		      n_project_teams = c(7L,13L,11L,18L))
knitr::kable(pba_pref_df, booktabs=TRUE,
             col.names = c("Semester", "Manual score", "Grouper score", 
			   "Class size", "No. topics", "No. project teams"),
             caption = "Breakdown of preference scores (per student). If grouper had been available, allocation could have been carried out in a more optimal manner, and much quicker!") %>% 
  kableExtra::kable_styling(font_size = 9, latex_options = c("hold_position"))


## ----pba-past-2, echo=FALSE, fig.align='center', fig.cap='Comparison between grouper allocation and manual allocation for preference-based groupings. The red line corresponds to mean preference scores if grouper had been available to carry out the allocation. The green line corresponds to mean preference scores from the actual manual allocations. While the improvement may not appear to be substantial, one must take note that the manual allocation process could take 4 - 5 days, while grouper takes minutes.', out.width='85%', fig.pos='ht'----
knitr::include_graphics("figures/pba_past_semesters_allocation.png")


## ----multi-role-dataset-summary, results='asis', echo=FALSE-------------------------------------------------------------
multi_role_dataset <- read.csv("data/derived/multi_role_dataset_summary.csv", check.names = FALSE)

knitr::kable(multi_role_dataset, caption = "Scale, role demand, and cohort composition of the three multi-role workload datasets.", position = "!h")


## ----load-ay2520, include=FALSE-----------------------------------------------------------------------------------------
# Read student records with anonymous labels and course-role demand.
students_ay2520 <- read.csv("data/raw/ay2520/students.csv", stringsAsFactors = FALSE)
demand_ay2520 <- read.csv("data/raw/ay2520/demand.csv", stringsAsFactors = FALSE)
pref_long_ay2520 <- read.csv("data/raw/ay2520/preferences_long.csv", stringsAsFactors = FALSE)

# Use stable ordering so row and column positions have a fixed meaning.
students_ay2520 <- students_ay2520[order(students_ay2520$student_id), ]
demand_ay2520 <- demand_ay2520[order(demand_ay2520$course_code), ]

# Convert long-form preference records into matrix row and column indices.
pref_long_ay2520$i <- match(pref_long_ay2520$student_id, students_ay2520$student_id)
pref_long_ay2520$j <- match(pref_long_ay2520$course_code, demand_ay2520$course_code)

# Build the student-by-course preference matrix.
P_ay2520 <- matrix(-99L, nrow = nrow(students_ay2520), ncol = nrow(demand_ay2520))
P_ay2520[cbind(pref_long_ay2520$i, pref_long_ay2520$j)] <- pref_long_ay2520$pref_score

# Build the course-by-role demand matrix in the role order expected by the model.
D_ay2520 <- as.matrix(demand_ay2520[, c("TA", "GR", "E")])


## ----multirole-extract-info---------------------------------------------------------------------------------------------
df_multirole <- extract_info(
  assignment = "multirole",
  student_df = students_ay2520[, c("student_id", "year", "past_ta", "past_gr")],
  d_mat = D_ay2520, p_ta_mat = P_ay2520, e_mode = "none", C = 4)


## ----multirole-prepare-model--------------------------------------------------------------------------------------------
model_multirole <- prepare_model(df_list = df_multirole, 
                                 assignment = "multirole",
                                 alpha_ta = 2, alpha_gr = NULL, 
                                 beta_ta = 1, beta_gr = NULL, 
                                 phi = 1, rho_ta = 10, rho_gr = NULL, 
                                 protected_year_ta = 1, 
                                 ta_protected_max = 1, e_max = 1)


## ----multirole-solve-assignment-----------------------------------------------------------------------------------------
multirole_solution <- solve_assignment(model = model_multirole, 
                                       assignment = "multirole", 
                                       solver = "glpk",
                                       student_df = students_ay2520, 
                                       course_codes = demand_ay2520$course_code,
                                       name_col = "student_id", verbose = FALSE)


## ----fig-multi-role-objective-comparison, fig.cap="Model and manual schedules compared by absolute objective value across three semesters. Both schedules are scored using the same policy weights. Taller bars represent more negative, and hence lower, objective values; under this policy, the optimized model schedule has a lower weighted objective than the manual schedule in all three semesters.", fig.alt="Grouped bar chart comparing the absolute objective values of model and manual schedules for AY2420, AY2510, and AY2520.", out.width="0.72\\linewidth", fig.pos="!htbp", echo=FALSE----
knitr::include_graphics("figures/multi_role_objective_comparison.pdf")


## ----fig-ay2520-distribution, fig.cap="AY2520 model workload distribution by anonymous student label and cohort year. Each stacked bar shows optimized current-semester TA, GR, and residual-support units together with previous-semester TA and GR workload carried into the annual balance. The dashed line marks the four-unit semester capacity. Faceting by cohort year highlights the Year-1 TA protection rule and the allocation of residual-support work to Years 2 to 4.", fig.alt="Stacked bar chart faceted by year showing AY2520 current and past workload components for anonymous student labels.", out.width="0.8\\linewidth", fig.pos="!htbp", echo=FALSE----
knitr::include_graphics("figures/ay2520_distribution.pdf")


## ----fig-multi-role-objective-term-gap, fig.cap="AY2420 weighted objective-term differences between manual and model schedules. Bars are manual-minus-model values under the manuscript policy weights. The preference term accounts for 125 objective units of the 125-unit total gap; the fairness term adds 8 units to the manual objective, the seniority residual-support term offsets the gap by 8 units, and the Year-1 slack term is unchanged.", fig.alt="Horizontal bar chart showing AY2420 manual-minus-model weighted differences for TA preference, TA fairness, seniority residual support, and Year-1 TA slack terms.", out.width="0.78\\linewidth", fig.pos="!htbp", echo=FALSE----
knitr::include_graphics("figures/multi_role_objective_term_gap.pdf")


## ----load-solver-runtime, include=FALSE---------------------------------------------------------------------------------
solver_runtime <- read.csv("data/derived/ay2520_solver_runtime.csv", check.names = FALSE)

runtime_summary <- solver_runtime %>%
  group_by(Solver) %>%
  summarise(runs = n(), objective = unique(Objective),
            mean_time = mean(Time_seconds),min_time = min(Time_seconds),
            max_time = max(Time_seconds), .groups = "drop")

glpk_runtime <- runtime_summary %>% filter(Solver == "glpk")
highs_runtime <- runtime_summary %>% filter(Solver == "highs")


## ----gui-run-command, eval=FALSE----------------------------------------------------------------------------------------
# library(shiny)
# runApp(system.file(file.path("shiny", "grouperWebApp", "app.R"),
#                    package = "grouper"))


## ----fig-grouper-webapp-home, fig.cap="Home page of the web application. The page acts as a model selector, routing users to the DBA, PBA, or multi-role workload workflow.", fig.alt="Screenshot of the grouper Shiny home page with three model cards.", out.width="0.86\\linewidth", fig.pos="!htbp", echo=FALSE----
knitr::include_graphics("figures/grouper_webapp_home.png")


## ----fig-grouper-webapp-multirole-results, fig.cap="Multi-role workload run summary and workload distribution view. The results page reports solver status and objective diagnostics, displays workload and preference-attainment views, shows the wide assignment table, and provides XLSX export for record-keeping.", fig.alt="Screenshot of the grouper Shiny multi-role workload run summary and workload distribution after a successful optimization run.", out.width="0.86\\linewidth", fig.pos="!htbp", echo=FALSE----
knitr::include_graphics("figures/grouper_webapp_multirole_results.png")

