# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit grouper.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------------------------------------------------------
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, fig.align = "center")

required_pkgs <- c(
  "grouper", "ompr", "ompr.roi", "ROI.plugin.glpk", "dplyr", "ggplot2"
)

for (pkg in required_pkgs) {
  if (!requireNamespace(pkg, quietly = TRUE)) {
    stop("Package not installed: ", pkg)
  }
}

suppressPackageStartupMessages({
  library(grouper)
  library(ompr)
  library(ompr.roi)
  library(ROI.plugin.glpk)
  library(dplyr)
  library(ggplot2)
  library(tidyverse)
})


## ----fig-package-architecture, fig.cap="High-level package architecture.", fig.alt="Workflow diagram showing higher-education inputs flowing through data processing, model building, and solving stages, with outputs for solver diagnostics and allocation tables.", out.width="0.92\\linewidth", echo=FALSE----
knitr::include_graphics("figures/workflow.png")


## -----------------------------------------------------------------------------------------------------------------------------
dba_gc_ex001


## -----------------------------------------------------------------------------------------------------------------------------
dba_ex1_list <- extract_info(assignment = "diversity", dframe = dba_gc_ex001, 
                        demographic_cols = 2, skills = 3, self_formed_groups = 4)

dba_ex1_model <- prepare_model(dba_ex1_list, assignment = "diversity", 
                               w1 = 1.0, w2 = 0.0, 
                               n_topics = 2, nmin = 2, nmax = 2, rmin = 1, rmax = 1 )

dba_ex1_result <- solve_model(dba_ex1_model, with_ROI(solver = "glpk"))


## -----------------------------------------------------------------------------------------------------------------------------
dba_ex1_output_df <- assign_groups(model_result = dba_ex1_result,  
                                   assignment = "diversity", dframe = dba_gc_ex001, 
                                   group_names = "groups")


## ----constructed-dba-2, echo=FALSE--------------------------------------------------------------------------------------------
knitr::kable(dba_ex1_output_df, booktabs=TRUE,
             col.names = c("topic", "rep", "group", "id", "major", "skill"),
             caption = "The assigned groupings for the constructed DBA dataset. Students 2 and 3 have been assigned to topic 1 and students 1 and 4 to topic 2.") %>% 
  kableExtra::kable_styling(latex_options = c("hold_position"))


## -----------------------------------------------------------------------------------------------------------------------------
pba_gc_ex002


## -----------------------------------------------------------------------------------------------------------------------------
pba_prefmat_ex002


## -----------------------------------------------------------------------------------------------------------------------------
pba_ex2_list <- extract_info(assignment = "preference", 
                             dframe = pba_gc_ex002, self_formed_groups = 2, 
                             pref_mat = pba_prefmat_ex002 )

pba_ex2_model <- prepare_model(pba_ex2_list, assignment = "preference", 
                               n_topics = 2, B = 2, nmin = 2, nmax = 2, 
                               rmin = 1, rmax = 1 )

pba_ex2_result <- solve_model(pba_ex2_model, with_ROI(solver = "glpk"))

pba_ex2_output_df <- assign_groups(model_result = pba_ex2_result, 
                                   assignment = "preference", 
                                   dframe = pba_gc_ex002, 
                                   params_list = list(n_topics = 2, B = 2), 
                                   group_names = "grouping" )


## ----constructed-pba-2, echo=FALSE--------------------------------------------------------------------------------------------
tmp <- arrange(pba_ex2_output_df, topic2, subtopic)
knitr::kable(tmp, booktabs=TRUE,
             col.names = c("topic", "subtopic", "rep", "group", "size", "id"),
             caption = "The assigned groupings for the constructed PBA dataset. The number of rows in this dataset is equal to the number of students in the course.") %>% 
  kableExtra::kable_styling(latex_options = c("hold_position"))


## ----dba-past-1, echo=FALSE, fig.align='center', fig.cap='Comparison between grouper allocation and manual allocation for diversity-based groupings in an interdisciplinary course. The top row corresponds to the outcomes if grouper had been available to carry out the allocation. The bottom row consists of the manual allocation outcomes. Notice that group 2 in the manual assignment was heavily imbalanced.', out.width='85%', fig.pos='ht'----
knitr::include_graphics("figures/dba_past_semesters_allocation.png")


## ----pba-past-1, echo=FALSE---------------------------------------------------------------------------------------------------
pba_pref_df <- tibble(sem = 1:4,
		      manual = c(8.16, 13.10, 12.70, 9.48),
		      grouper = c(9.47, 13.30, 13.50, 9.66),
		      class_size = c(62L, 108L, 89L, 151L),
		      n_topics = c(4L,7L,7L,5L),
		      n_project_teams = c(7L,13L,11L,18L))
knitr::kable(pba_pref_df, booktabs=TRUE,
             col.names = c("Semester", "Manual score", "Grouper score", 
			   "Class size", "No. topics", "No. project teams"),
             caption = "Breakdown of preference scores (per student). If grouper had been available, allocation could have been carried out in a more optimal manner, and much quicker!") %>% 
  kableExtra::kable_styling(font_size = 9, latex_options = c("hold_position"))


## ----pba-past-2, echo=FALSE, fig.align='center', fig.cap='Comparison between grouper allocation and manual allocation for preference-based groupings. The red line corresponds to mean preference scores if grouper had been available to carry out the allocation. The green line corresponds to mean preference scores from the actual manual allocations. While the improvement may not appear to be substantial, one must take note that the manual allocation process could take 4 - 5 days, while grouper takes minutes.', out.width='85%', fig.pos='ht'----
knitr::include_graphics("figures/pba_past_semesters_allocation.png")


## ----load-multirole-evidence, include=FALSE-----------------------------------------------------------------------------------
multi_role_dataset <- read.csv(
  "data/derived/multi_role_dataset_summary.csv",
  check.names = FALSE
)
solver_runtime <- read.csv(
  "data/derived/ay2520_solver_runtime.csv",
  check.names = FALSE
)

runtime_summary <- solver_runtime |>
  group_by(Solver) |>
  summarise(
    runs = n(),
    objective = unique(Objective),
    mean_time = mean(Time_seconds),
    min_time = min(Time_seconds),
    max_time = max(Time_seconds),
    .groups = "drop"
  )

glpk_runtime <- runtime_summary |> filter(Solver == "glpk")
highs_runtime <- runtime_summary |> filter(Solver == "highs")


## ----multi-role-dataset-summary, results='asis', echo=FALSE-------------------------------------------------------------------
knitr::kable(
  multi_role_dataset,
  caption = "Scale, role demand, and cohort composition of the three multi-role workload datasets.",
  position = "!h"
)


## ----load-ay2520, include=FALSE-----------------------------------------------------------------------------------------------
# Read anonymized student records and course-role demand.
students_ay2520 <- read.csv(
  "data/raw/ay2520/students.csv",
  stringsAsFactors = FALSE
)
demand_ay2520 <- read.csv(
  "data/raw/ay2520/demand.csv",
  stringsAsFactors = FALSE
)
pref_long_ay2520 <- read.csv(
  "data/raw/ay2520/preferences_long.csv",
  stringsAsFactors = FALSE
)

# Use stable ordering so row and column positions have a fixed meaning.
students_ay2520 <- students_ay2520[order(students_ay2520$student_id), ]
demand_ay2520 <- demand_ay2520[order(demand_ay2520$course_code), ]

# Convert long-form preference records into matrix row and column indices.
pref_long_ay2520$i <- match(pref_long_ay2520$student_id, students_ay2520$student_id)
pref_long_ay2520$j <- match(pref_long_ay2520$course_code, demand_ay2520$course_code)

# Build the student-by-course preference matrix.
P_ay2520 <- matrix(
  -99L,
  nrow = nrow(students_ay2520),
  ncol = nrow(demand_ay2520)
)
P_ay2520[
  cbind(pref_long_ay2520$i, pref_long_ay2520$j)
] <- pref_long_ay2520$pref_score

# Build the course-by-role demand matrix in the role order expected by the model.
D_ay2520 <- as.matrix(demand_ay2520[, c("TA", "GR", "E")])


## ----phd-extract-info---------------------------------------------------------------------------------------------------------
df_phd <- extract_info(
  assignment = "phd",
  student_df = students_ay2520[, c("student_id", "year", "past_ta", "past_gr")],
  p_mat = P_ay2520,
  d_mat = D_ay2520,
  e_mode = "none",
  C = 4
)


## ----phd-prepare-model--------------------------------------------------------------------------------------------------------
model_phd <- prepare_model(
  df_list = df_phd,
  assignment = "phd",
  alpha = 2,
  beta = 1,
  phi = 1,
  rho = 10,
  t_max_y1 = 1,
  e_max = 1,
  C = 4
)


## ----phd-solve-assignment-----------------------------------------------------------------------------------------------------
phd_solution <- solve_assignment(
  model = model_phd,
  assignment = "phd",
  solver = "glpk",
  student_df = students_ay2520,
  course_codes = demand_ay2520$course_code,
  name_col = "student_id",
  verbose = FALSE
)


## ----fig-multi-role-objective-comparison, fig.cap="Model and manual schedules compared by absolute objective value across three semesters.", fig.alt="Grouped bar chart comparing the absolute objective values of model and manual schedules for AY2420, AY2510, and AY2520.", out.width="0.72\\linewidth", fig.pos="!htbp", echo=FALSE----
knitr::include_graphics("figures/multi_role_objective_comparison.pdf")


## ----fig-ay2520-distribution, fig.cap="AY2520 model workload distribution by anonymized student and cohort year.", fig.alt="Stacked bar chart faceted by year showing AY2520 current and past workload components for anonymized students.", out.width="0.8\\linewidth", fig.pos="!htbp", echo=FALSE----
knitr::include_graphics("figures/ay2520_distribution.pdf")


## ----fig-multi-role-objective-term-gap, fig.cap="AY2420 weighted objective-term differences between manual and model schedules.", fig.alt="Horizontal bar chart showing AY2420 manual-minus-model weighted differences for preference, fairness, seniority residual support, and Year-1 slack terms.", out.width="0.78\\linewidth", fig.pos="!htbp", echo=FALSE----
knitr::include_graphics("figures/multi_role_objective_term_gap.pdf")


## ----gui-run-command, eval=FALSE----------------------------------------------------------------------------------------------
# library(shiny)
# runApp(system.file(file.path("shiny", "grouperWebApp", "app.R"),
#                    package = "grouper"))


## ----fig-grouper-webapp-home, fig.cap="Home page of the web application.", fig.alt="Screenshot of the grouper Shiny home page with three model cards.", out.width="0.86\\linewidth", fig.pos="!htbp", echo=FALSE----
knitr::include_graphics("figures/grouper_webapp_home.png")


## ----fig-grouper-webapp-multirole-results, fig.cap="Multi-role workload results view.", fig.alt="Screenshot of the grouper Shiny multi-role workload results view after a successful optimization run.", out.width="0.86\\linewidth", fig.pos="!htbp", echo=FALSE----
knitr::include_graphics("figures/grouper_webapp_multirole_results.png")

