# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit grouper.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, fig.align = "center")

required_pkgs <- c(
  "grouper", "ompr", "ompr.roi", "ROI.plugin.glpk", "dplyr", "ggplot2"
)

for (pkg in required_pkgs) {
  if (!requireNamespace(pkg, quietly = TRUE)) {
    stop("Package not installed: ", pkg)
  }
}

suppressPackageStartupMessages({
  library(grouper)
  library(ompr)
  library(ompr.roi)
  library(ROI.plugin.glpk)
  library(dplyr)
  library(ggplot2)
})


## ----fig-package-architecture, fig.cap="High-level package architecture.", fig.alt="Workflow diagram showing higher-education inputs flowing through data processing, model building, and solving stages, with outputs for solver diagnostics and allocation tables.", out.width="0.92\\linewidth", echo=FALSE----
knitr::include_graphics("figures/workflow.png")


## ----load-multirole-evidence, include=FALSE-----------------------------------
multi_role_dataset <- read.csv(
  "data/derived/multi_role_dataset_summary.csv",
  check.names = FALSE
)
solver_runtime <- read.csv(
  "data/derived/ay2520_solver_runtime.csv",
  check.names = FALSE
)

runtime_summary <- solver_runtime |>
  group_by(Solver) |>
  summarise(
    runs = n(),
    objective = unique(Objective),
    mean_time = mean(Time_seconds),
    min_time = min(Time_seconds),
    max_time = max(Time_seconds),
    .groups = "drop"
  )

glpk_runtime <- runtime_summary |> filter(Solver == "glpk")
highs_runtime <- runtime_summary |> filter(Solver == "highs")


## ----multi-role-dataset-summary, results='asis', echo=FALSE-------------------
knitr::kable(
  multi_role_dataset,
  caption = "Scale, role demand, and cohort composition of the three multi-role workload datasets.",
  position = "!h"
)


## ----load-ay2520, include=FALSE-----------------------------------------------
# Read anonymized student records and course-role demand.
students_ay2520 <- read.csv(
  "data/raw/ay2520/students.csv",
  stringsAsFactors = FALSE
)
demand_ay2520 <- read.csv(
  "data/raw/ay2520/demand.csv",
  stringsAsFactors = FALSE
)
pref_long_ay2520 <- read.csv(
  "data/raw/ay2520/preferences_long.csv",
  stringsAsFactors = FALSE
)

# Use stable ordering so row and column positions have a fixed meaning.
students_ay2520 <- students_ay2520[order(students_ay2520$student_id), ]
demand_ay2520 <- demand_ay2520[order(demand_ay2520$course_code), ]

# Convert long-form preference records into matrix row and column indices.
pref_long_ay2520$i <- match(pref_long_ay2520$student_id, students_ay2520$student_id)
pref_long_ay2520$j <- match(pref_long_ay2520$course_code, demand_ay2520$course_code)

# Build the student-by-course preference matrix.
P_ay2520 <- matrix(
  -99L,
  nrow = nrow(students_ay2520),
  ncol = nrow(demand_ay2520)
)
P_ay2520[
  cbind(pref_long_ay2520$i, pref_long_ay2520$j)
] <- pref_long_ay2520$pref_score

# Build the course-by-role demand matrix in the role order expected by the model.
D_ay2520 <- as.matrix(demand_ay2520[, c("TA", "GR", "E")])


## ----phd-extract-info---------------------------------------------------------
df_phd <- extract_info(
  assignment = "phd",
  student_df = students_ay2520[, c("student_id", "year", "past_ta", "past_gr")],
  p_mat = P_ay2520,
  d_mat = D_ay2520,
  e_mode = "none",
  C = 4
)


## ----phd-prepare-model--------------------------------------------------------
model_phd <- prepare_model(
  df_list = df_phd,
  assignment = "phd",
  alpha = 2,
  beta = 1,
  phi = 1,
  rho = 10,
  t_max_y1 = 1,
  e_max = 1,
  C = 4
)


## ----phd-solve-assignment-----------------------------------------------------
phd_solution <- solve_assignment(
  model = model_phd,
  assignment = "phd",
  solver = "glpk",
  student_df = students_ay2520,
  course_codes = demand_ay2520$course_code,
  name_col = "student_id",
  verbose = FALSE
)


## ----fig-multi-role-objective-comparison, fig.cap="Model and manual schedules compared by absolute objective value across three semesters.", fig.alt="Grouped bar chart comparing the absolute objective values of model and manual schedules for AY2420, AY2510, and AY2520.", out.width="0.72\\linewidth", fig.pos="!htbp", echo=FALSE----
knitr::include_graphics("figures/multi_role_objective_comparison.pdf")


## ----fig-ay2520-distribution, fig.cap="AY2520 model workload distribution by anonymized student and cohort year.", fig.alt="Stacked bar chart faceted by year showing AY2520 current and past workload components for anonymized students.", out.width="0.8\\linewidth", fig.pos="!htbp", echo=FALSE----
knitr::include_graphics("figures/ay2520_distribution.pdf")


## ----fig-multi-role-objective-term-gap, fig.cap="AY2420 weighted objective-term differences between manual and model schedules.", fig.alt="Horizontal bar chart showing AY2420 manual-minus-model weighted differences for preference, fairness, seniority residual support, and Year-1 slack terms.", out.width="0.78\\linewidth", fig.pos="!htbp", echo=FALSE----
knitr::include_graphics("figures/multi_role_objective_term_gap.pdf")


## ----gui-run-command, eval=FALSE----------------------------------------------
# library(shiny)
# runApp(system.file(file.path("shiny", "grouperWebApp", "app.R"),
#                    package = "grouper"))


## ----fig-grouper-webapp-home, fig.cap="Home page of the web application.", fig.alt="Screenshot of the grouper Shiny home page with three model cards.", out.width="0.86\\linewidth", fig.pos="!htbp", echo=FALSE----
knitr::include_graphics("figures/grouper_webapp_home.png")


## ----fig-grouper-webapp-multirole-results, fig.cap="Multi-role workload results view.", fig.alt="Screenshot of the grouper Shiny multi-role workload results view after a successful optimization run.", out.width="0.86\\linewidth", fig.pos="!htbp", echo=FALSE----
knitr::include_graphics("figures/grouper_webapp_multirole_results.png")

